spring:
  application:
    name: vote-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create-drop # todo
    show-sql: true
  liquibase:
    change-log: db/changelog/db.changelog-master.xml
    enabled: false # todo
  thymeleaf:
    cache: false

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  address: ${SERVER_ADDRESS:localhost}
  port: ${SERVER_PORT:8080}

#server-custom:
#  url-address: ${SERVER_URL:http://${server.address}:${server.port}}